# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 162d39ff33f7ef8429462ecba43a8b30a11bb810bcaba48dc10eb0b7db45ba5749424aec7c9c044dcdeec483431759c9b464fff38fcf7029ac195be0e4f50472

test:
  secret_key_base: c7cb0e15ba4cd71b0aec188bd09bb83d362d3eea8859d97634acfab88476a6f9d8a68fbc168321d36365a5a5eff88e305eb65d65c15be9fc749a645c8f940366

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
